name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install prettier by pnpm
        run: pnpm install --frozen-lockfile
      - name: Check format
        run: pnpm run lint:fmt

  lint:
    strategy:
      matrix:
        renovate_version: [37, 36]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install linter
        run: npm install -g renovate@${{ matrix.renovate_version }}

      - name: Lint renovate config
        run: renovate-config-validator default.json && renovate-config-validator *.json5
