name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        renovate_version: [37, 36]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install linter
        run: npm install -g prettier renovate@${{ matrix.renovate_version }}

      - name: Lint renovate config
        run: renovate-config-validator default.json && renovate-config-validator *.json5

      - name: Check format
        run: prettier --check .
